#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
GROUP=dev.phillipslabs
VERSION_NAME=0.1.0
POM_URL=https://github.com/daphil19/tuskt
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_SCM_URL=https://github.com/daphil19/tuskt
POM_SCM_CONNECTION=scm:git:git://github.com/daphil19/tuskt.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/daphil19/tuskt.git
POM_DEVELOPER_ID=daphil19
POM_DEVELOPER_NAME=David Phillips
POM_DEVELOPER_URL=https://github.com/daphil19
KTLINT_CLI_VERSION=1.8.0
#Kotlin
kotlin.code.style=official
#MPP
kotlin.mpp.enableCInteropCommonization=true
