[versions]
# NOTE this is lower than the minimum version needed to run gradle, to help maximize compatibility
jdk = "17"
kotlin = "2.3.21"
android-compileSdk = "36"
android-minSdk = "21"
# ktor versioning defined in version catalog in settings.gradle.kts
#ktor = "3.4.0"
ktlint-cli = "1.8.0"
ktlint-plugin = "14.2.0"
detekt = "1.23.8"
android-plugin = "9.2.1"
shadow = "9.4.1"
versions-plugin = "0.53.0"
jimfs = "1.3.1"
kotlinLogging = "8.0.01"
coroutines = "1.11.0"
vanniktech = "0.36.0"
jetbrainsChangelog = "2.5.0"
kotlinx-serialization-json = "1.11.0"

[libraries]
#ktor-version-catalog = { module = "io.ktor:ktor-version-catalog", version.ref = "ktor" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { module = "com.android.kotlin.multiplatform.library:com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "android-plugin" }
ktlint-gradlePlugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-plugin" }
detekt-gradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
benManes-gradlePlugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versions-plugin" }
jetbrains-changelogPlugin = { module = "org.jetbrains.changelog:org.jetbrains.changelog.gradle.plugin", version.ref = "jetbrainsChangelog" }
jimfs = { module = "com.google.jimfs:jimfs", version.ref = "jimfs" }
kotlinLogging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlinLogging"}
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
vanniktech-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

[bundles]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
changelog = { id = "org.jetbrains.changelog", version.ref = "jetbrainsChangelog" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
#ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
